[package]
name = "quanta"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
env = "1.0.1"
lazy_static = "1.5.0"
once_cell = "1.21.3"
quote = "1.0.40"
smol_str = "0.3.2"
syn = "2.0.100"
